### PR TITLE
Fix deploy cmdlets

### PR DESCRIPTION
**Pull request by levesquesamuel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | yes but not created (The term "Connect-SPOnline" is not recognized.)

#### What's in this Pull Request?

Fix the errors when deploying after the December 2016 changes of the PnP PowerShell Cmdlets *-SPO* to *-PnP*.

#### Guidance
December 2016 Release of PnP-PowerShell is now a prerequisite.

### CODE REVIEW

**Comment by levesquesamuel** [comment]
Done!

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by VesaJuvonen** [comment]
Will merge this for the January release. Adding though also @FranckyC here to let him know. Technically there should be alias entries for the PnP cmdlet's with the December release, so that there's no renaming required, but no harm doing this. This will also ensure that people are using latest PowerShell version, which is good. Thx Samuel for sharing.

**Comment by FranckyC** [comment]
@VesaJuvonen Already confirmed with @levesquesamuel ;). Sorry for the delay (and happy new year btw!).

**Comment by VesaJuvonen** [comment]
thx @FranckyC for coming back and no worries. Happy new year to you as well.

**Pull request merged**
