### PR TITLE
TaxonomyPicker without JSOM

### PR DESCRIPTION
**Pull request by countvm**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | no 
| New sample?      | yes

#### What's in this Pull Request?

MVC5 TaxonomyPicker that requires no add-in web based on Core.TaxonomyPicker

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Alexander, really great work on this. I'll slightly change the folder name in the samples folder after merging, but no changes on the actual implementation. This is really valuable sample. Any change you'd like to demonstrate this in the monthly community call with 10-15 min demo? - Call would be on next Tuesday 11th of April at 5 PM CET (Sweden time).

**Comment by VesaJuvonen** [comment]
Hi Alexander, unfortunately we can't reschedule our monthly community calls, since these are open monthly calls for the community to attend and we cover the latest changes in PnP side with demos - these are also getting recorded and shared from PnP YouTube channel. See for example last month's call at - https://www.youtube.com/watch?v=u-ueS8pTAz4. Typically these get roughly 60-80 attendees and we start by doing 15-20 summary on slides, before moving to demos. 

We can agree that you'll be the first person to demo, which would mean roughtly 17:20-17:35 from timing perspective. If this is an issue from availability perspective, now worries. Just wanted to check if we could do this and get the sample recorded. 

Please let us know. We'll push out the agenda for monthly community call during weekend as part of the monthly communications - see for example previous monthly notes at https://dev.office.com/blogs/pnp-march-2017-release.

**Comment by countvm** [comment]
Yes that will work for me. If I have some updates before the communitycall, should I just make another pull request or wait until after the demo?

BR
Alex

**Comment by VesaJuvonen** [comment]
Since we will be doing our master merge during weekend, would suggest to delay PRs until after the demo. You can absolutely explain what's new etc. You can download invite for the call from http://aka.ms/sppnp-call. We'll update you as presenter when you join for the demo. I won't be there personally (family vacation), but other Core team members are up to date on this demo.

**Pull request merged**
