### PR TITLE
PnP Starter Intranet v2.0 update

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes

#### What's in this Pull Request?

Big update on the PnP Starter Intranet solution. Now the entire solution design comes from a real customer allowing us to share with the community. Also, a lot of improvements have been made (performances, code structure, language management, etc.)

All the folder content "Business.StarterIntranet" can be replaced by the new one. Resolving merge conflicts for each file would be very complicated.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi @FranckyC, this looks really good and great that this is still evolving. There are however quite a few merge conflicts with this one, which seems strange considering that you've been the person creating the previous version as well. Can you double check the status with the changes - thx. We can certainly resolve the conflicts one-by-one, but wanted to double check the status from your side one more time.

**Comment by FranckyC** [comment]
Hi @VesaJuvonen, the code has been completely reorganized. This is why there are a lot of conflicts on this one. The simpliest thing would be to replace the folder content but I don't think is it possible on your side.

Also the code has been paste from an other repo (private) so there is theoretically more than 5 commits overall. I had to remove the older content and then paste the new code.

**Comment by VesaJuvonen** [comment]
thx @FranckyC - I'll get this processed for the September master merge for sure, which is scheduled for 8th of Sep - so way before the monthly call. Happy to have you do an updated demo on this in the monthly call, if you are interested? - that would be on Tuesday 12th of September at 8 AM PT.

**Comment by FranckyC** [comment]
Hi @VesaJuvonen, yes sure (see my mail, I have something to suggest for the call). Otherwise, if you have trouble for merging don't hesitate to contact me.

**Comment by pakonawala** [comment]
Hi Frank nice sample you have there i tried to install you latest release from scratch and having sass loader issues. I tried all i could to get it working but no luck. Please look at the error below.

Thanks

**Comment by pakonawala** [comment]
Child extract-text-webpack-plugin:
       [0] ../~/css-loader!../~/resolve-url-loader!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./styles/css/icscalendargenerator.scss 3.06 kB {0} [built] [failed] [1 error]

    ERROR in ../~/css-loader!../~/resolve-url-loader!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./styles/css/icscalendargenerator.scss
    Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\vendor'
        at Error (native)
        at Object.fs.readdirSync (fs.js:951:18)
        at Object.getInstalledBinaries (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\extensions.js:123:13)
        at foundBinariesList (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:20:15)
        at foundBinaries (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:15:5)
        at Object.module.exports.missingBinary (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:45:5)
        at module.exports (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\binding.js:15:30)
        at Object.<anonymous> (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at loadLoader (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)

**Comment by FranckyC** [comment]
Hi @pakonawala. What version of webpack do you have globally? This sample works with the 2.4.1 webpack version. Let me know

**Comment by FranckyC** [comment]
Hi @VesaJuvonen , any updates on this PR?

**Comment by VesaJuvonen** [comment]
Manually merged due massive amount of merge conflict. Should be all good now.

**Comment by FranckyC** [comment]
Hi @VesaJuvonen , just checked and it seems it is the version 1.0.0 not the 2.0.0. :(. Folders are not matching with the new solution at all. Maybe if I create a brand new folder with update solution would be easier. Let me know.

**Comment by VesaJuvonen** [comment]
I had to basically move everything manually due the tens and tens of merge conflicts on this PR. Happy to merge things again, if you pinpoint me to the right location where you have the v2.0 version, so that we can double check and ensure that we get it right.

**Comment by FranckyC** [comment]
@VesaJuvonen , I will submit an other PR with a brand new folder to avoid merge conflicts.

**Comment by VesaJuvonen** [comment]
Let's not change the folder name - since that would break all existing links across the Internet - rather either update the files in this folder or pinpoint me to the right location from where I can pull down the right version.

**Comment by FranckyC** [comment]
The latest code is available in my [feature branch](https://github.com/FranckyC/PnP/tree/feature/starter-intranet-v2.0/Solutions/Business.StarterIntranet). All the preivous content can be replaced.  You can see my new PR.

**Pull request closed without merging**
