### PR TITLE
Added webparts to the PnP provisioning template for aspx pages

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| Related issues?  | https://github.com/SharePoint/PnP-Sites-Core/issues/866

#### What's in this Pull Request?

Added webparts to the PnP provisioning template for aspx pages. I removed them temporarly because webparts provisioning does not work with SharePoint 2013/2016 on-premises with the PnP January 2017 release (issue https://github.com/SharePoint/PnP-Sites-Core/issues/866). This issue seems to be fixed with the February 2017 release.

### CODE REVIEW

**Comment by FranckyC** [comment]
Hi @VesaJuvonen do you think it would be possible to merge this before the next release? I forgot to re-add webparts in the template :(. Thanks!

**Comment by VesaJuvonen** [comment]
thx for following up - yes - I'll get this merged today. Hopefully in next hour.

**Comment by VesaJuvonen** [comment]
All good actually. Thx for the submission - good to have this updated. Would you be btw up for showing updates on the next monthly community call on next Tuesday (8 AM PST)? - would be good demo to show the updates since autumn release and refresh the field on what this contains. This is one of the most viewed samples in the catalog currently, so there's clearly interest.

**Comment by FranckyC** [comment]
@VesaJuvonen Yes absolutely! I can do a 15-20 minutes presentation for the next webcast.

**Pull request merged**
