### PR TITLE
Modern and automated provisioning by using a Bot, Flow, Azure Function and SPFx

### PR DESCRIPTION
**Pull request by giuleon**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?

This sample demonstrates how to integrate a typical enterprise scenario where the user can submit a creation's request for a new SharePoint team site, communication site or a Microsoft team through a Node.js Bot (App Only) which is available on Teams, Skype, Direct line and so on. The request is stored in a SharePoint list accessible only by an admin which can approve it, triggering a Microsoft Flow that contains the logic necessary to send an email to the end user and the admin in order to notify that the process is started. After that, if a request has the status equal to "Approved" the latter is processed by calling an Azure c# function that creates a SharePoint team site, communication site or a Microsoft Team. Microsoft Flow receives a response from the Azure function with HTTP status 200, at the end the user receives an email that notifies the end of the process. Furthermore, there is also a SharePoint Framework Application Customizer which allows the user to interact with the Bot by leveraging the capabilities of the direct line from a SharePoint site.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Really cool setup and great work on the documentation as well. Good to have this scenario covered using this tech as well. Would you be available for a live demo and tech walkthrough on this for the "general Dev" SIG on 8th of March? - Typical Thursday timing.

**Comment by giuleon** [comment]
Certainly consider me inside 👌

**Comment by VesaJuvonen** [comment]
Cool - So let's do that then for 8th of March at 7 AM PT (3 PM GMT). Cool demo to demonstrate. Will add that to the agenda right away so won't forget.

**Comment by giuleon** [comment]
Thanks Vesa

**Comment by DeanGross** [comment]
How does this compare to the approach described at https://techcommunity.microsoft.com/t5/SharePoint-Blog/MVP-Blog-Provisioning-an-Office-365-group-with-an-approval-flow/ba-p/166410

**Comment by giuleon** [comment]
The Azure Function makes use of OfficeDevPnP.Core in order to create the SharePoint sites (team site and communications site), regarding Teams are used the Microsoft Graph APIs which are also consumed in the Martina's solution.

**Comment by VesaJuvonen** [comment]
hi @giuleon - I know that due time zones you are getting this slightly late - but just confirming again that you will be on the agenda for tomorrow 8th of March SIG call. Will push out the first note on the call agenda right now and then re-enforce the message or repeat the invite after that.

**Comment by giuleon** [comment]
Hi @VesaJuvonen yes I'll be there

**Pull request merged**
