### PR TITLE
Asp net core.2.0.authentication

### PR DESCRIPTION
**Pull request by AquilaSands**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | no
| Related issues?  | none

#### What's in this Pull Request?

Updated the AspNetCore.Authentication solution to work with the .net core 2.0 authentication middleware changes as described here https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Aquila, we appreciate the submission and sorry for the small delay. We will process this as soon possible.

**Comment by SharePointRadi** [comment]
Hello AquilaSands,

thank you for the pull request. Things look good. Could you please do a few changes before we merge it in:

- Revert it to build for .NET Framework 4.6.1 unless it absolutely needs .NET Framework 4.7 (as far as I can tell it is OK in 4.6.1). This is only to avoid a new dependency on anyone who is using it without any need. This also reduces the impact of this PR on SharePoint.IdentityModel.Extensions, which is referenced in the Core PnP library
- Please get rid of Extensions/IgnoreSslErrorsConnectionFilter.cs - we won't need it anymore
- no need for the ////.UseKestrel(options => comments either - they will not be needed
- we can get rid of accidential project.lock.json files

Good stuff!

**Comment by AquilaSands** [comment]
Hi,

- I've reverted the build to .NET Framework 4.6.1, I've tested this locally and everything still works.
- Extensions/IgnoreSslErrorsConnectionFilter.cs has been removed.
- The code for .UseKestrel(options => has been uncommented to enable localhost development and remove the need for an Azure App Service, I have therefore removed the call to .UseAzureAppServices()  because of this. I have also removed the call to .UseUrls("https://localhost:5000") as well as this is no longer used by Kestrel.
- There were no project.lock.json files as these had already been removed by the xproj to csproj upgrade process.

Do I need to issue a new pull request for these changes?

**Comment by SharePointRadi** [comment]
Thanks, AquilaSands. Everything looks good, we will merge this PR ASAP.

**Comment by VesaJuvonen** [comment]
thx @AquilaSands for this one and @SharePointRadi for the review. Great to get this processed and merged.

**Pull request merged**
